"""
Embedding generation service.

Architecture note:
    Embeddings are generated by calling OpenAI's embedding API.
    The key production concerns here are:

    1. Batching: OpenAI's API accepts up to 2048 inputs per request.
       Sending chunks one-by-one is wasteful — we batch them.
       A document with 50 chunks = 1 API call (batched), not 50 calls.

    2. Rate limiting: OpenAI has per-minute token limits per organization.
       For large documents, we may need to add delays between batches.
       The OpenAI SDK handles rate limit retries automatically if configured.

    3. Retry logic: transient network failures, 429s, and 503s are retried
       with exponential backoff. The SDK handles this if max_retries is set.

    4. Cost tracking: we log the exact number of tokens embedded so the
       analytics dashboard can compute dollar costs (text-embedding-3-small
       costs $0.02 per million tokens as of 2024).

    5. Model pinning: the embedding model is stored alongside the document
       record. This prevents the silent failure of querying with a different
       model than what was used for indexing.

Batch size decision (100 chunks per batch):
    - OpenAI allows up to 2048 inputs per request
    - 100 is conservative but safe for large chunks (512 tokens each)
    - Total tokens per batch: 100 × 512 = 51,200 tokens (well under limits)
    - At 100 chunks/batch, a 1000-chunk document requires 10 API calls

Failure modes:
    - API key invalid: 401 on first call — propagates up, document marked FAILED
    - Rate limit hit (429): SDK retries with backoff, up to max_retries times
    - Timeout: SDK raises APITimeoutError — propagates up, document marked FAILED
    - Context length exceeded: chunk is too long for the model — shouldn't happen
      at 512 tokens, but add a safety check for production
    - Empty string input: OpenAI rejects empty strings with a 400 error

Scaling consideration:
    At scale, embedding generation becomes the bottleneck and the cost center.
    Options:
    - Self-host a smaller model (sentence-transformers) for cost reduction
    - Cache embeddings for identical chunks (rare but possible for templates)
    - Use OpenAI's batch API for non-realtime workloads (50% cheaper, async)
"""

from dataclasses import dataclass

from openai import AsyncOpenAI, APIError, RateLimitError

from app.core.config import get_settings
from app.core.app_logging import get_logger
from app.services.chunker import TextChunk

logger = get_logger(__name__)

BATCH_SIZE = 100  # chunks per API call


@dataclass
class EmbeddedChunk:
    """A chunk paired with its embedding vector."""
    chunk: TextChunk
    embedding: list[float]  # 1536-dimensional vector for text-embedding-3-small


async def embed_chunks(chunks: list[TextChunk]) -> list[EmbeddedChunk]:
    """
    Generate embeddings for all chunks, batched to minimize API calls.

    Returns EmbeddedChunk objects pairing each TextChunk with its vector.
    Order is preserved — embedded_chunks[i].chunk == chunks[i].
    """
    if not chunks:
        return []

    settings = get_settings()
    client = AsyncOpenAI(
        api_key=settings.openai_api_key,
        max_retries=settings.openai_max_retries,
        timeout=settings.openai_timeout,
    )

    embedded: list[EmbeddedChunk] = []
    total_tokens = 0

    # Process in batches
    for batch_start in range(0, len(chunks), BATCH_SIZE):
        batch = chunks[batch_start: batch_start + BATCH_SIZE]
        batch_texts = [c.text for c in batch]

        # Safety check: OpenAI rejects empty strings
        for i, text in enumerate(batch_texts):
            if not text.strip():
                raise ValueError(
                    f"Chunk at index {batch_start + i} is empty after stripping. "
                    f"This should have been filtered by the chunker."
                )

        logger.info(
            "embedding_batch_started",
            batch_start=batch_start,
            batch_size=len(batch),
            total_chunks=len(chunks),
            model=settings.openai_embedding_model,
        )

        try:
            response = await client.embeddings.create(
                model=settings.openai_embedding_model,
                input=batch_texts,
                dimensions=settings.openai_embedding_dimensions,
                # encoding_format="float" is the default — returns list[float]
                # "base64" is faster for large batches but requires decoding
            )
        except RateLimitError as exc:
            logger.error(
                "embedding_rate_limit",
                batch_start=batch_start,
                error=str(exc),
                hint="Consider reducing batch size or adding delays between batches",
            )
            raise
        except APIError as exc:
            logger.error(
                "embedding_api_error",
                batch_start=batch_start,
                status_code=exc.status_code,
                error=str(exc),
            )
            raise

        # Validate response shape
        if len(response.data) != len(batch):
            raise ValueError(
                f"OpenAI returned {len(response.data)} embeddings for {len(batch)} inputs. "
                f"This should never happen — indicates an API issue."
            )

        for chunk, embedding_obj in zip(batch, response.data):
            embedded.append(EmbeddedChunk(
                chunk=chunk,
                embedding=embedding_obj.embedding,
            ))

        batch_tokens = response.usage.total_tokens
        total_tokens += batch_tokens

        logger.info(
            "embedding_batch_completed",
            batch_start=batch_start,
            batch_size=len(batch),
            tokens_used=batch_tokens,
            # text-embedding-3-small: $0.020 per 1M tokens
            estimated_cost_usd=round(batch_tokens * 0.00000002, 6),
        )

    logger.info(
        "embedding_completed",
        total_chunks=len(chunks),
        total_tokens=total_tokens,
        total_cost_usd=round(total_tokens * 0.00000002, 6),
        model=settings.openai_embedding_model,
    )

    return embedded
